//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITYFRAMEWORK
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY
    {
        public int ID { get; set; }
        public Nullable<int> PERSONID { get; set; }
        public string NAME { get; set; }
    
        public virtual PERSONAL PERSONAL { get; set; }

        public COMPANY()
        {

        }

        public COMPANY(int? pERSONID, string nAME)
        {
            PERSONID = pERSONID;
            NAME = nAME;
        }
    }
}
