//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITYFRAMEWORK
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSONAL()
        {
            this.COMPANies = new HashSet<COMPANY>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string POSITION { get; set; }
        public Nullable<short> AGE { get; set; }
        public string COUNTRY { get; set; }

        public PERSONAL(string nAME, string sURNAME, string pOSITION, short? aGE, string cOUNTRY)
        {
            NAME = nAME;
            SURNAME = sURNAME;
            POSITION = pOSITION;
            AGE = aGE;
            COUNTRY = cOUNTRY;
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPANY> COMPANies { get; set; }
    }
}
